package agentrules

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"strings"
)

// pointerMarker identifies the varvig pointer block in AGENTS.md. Its presence
// (or any literal mention of the generated filename) means the pointer is
// already there and AGENTS.md is never touched again.
const pointerMarker = "<!-- varvig:pointer -->"

// GeneratedName and PointerName are the two files this feature manages.
const (
	GeneratedName = "VARVIG-AGENTS.md"
	PointerName   = "AGENTS.md"
)

// RepoFacts are the repo-local inputs to generation, resolved by the caller
// (the CLI) from the repository. Keeping them as plain data keeps generation
// pure and deterministic and lets tests pin them.
type RepoFacts struct {
	// AcceptanceGates are the gate/event names configured in the repo (e.g.
	// "pre-commit"), sorted. Empty means none are configured, which renders an
	// explicit TODO rather than a silent omission.
	AcceptanceGates []string
	// TestCommand is the repo's configured acceptance/test command, if any.
	TestCommand string
}

// Generate renders VARVIG-AGENTS.md in full for the given version and repo
// facts. It is deterministic: the only variable inputs are version (which lands
// only in the header) and facts. The returned surface hash is a function of the
// body — everything except the version-bearing header — so a version bump alone
// does not change it, but any surface or repo-fact change does.
func Generate(version string, facts RepoFacts) (content, surface string) {
	body := renderBody(facts)
	surface = surfaceHash(body)
	header := renderHeader(version, surface)
	return header + body, surface
}

// surfaceHash is the first four bytes of sha256(body), hex-encoded (eight
// chars), matching the `surface <hash>` form in the header.
func surfaceHash(body string) string {
	sum := sha256.Sum256([]byte(body))
	return hex.EncodeToString(sum[:4])
}

func renderHeader(version, surface string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "<!-- generated by varvig %s — do not edit -->\n", version)
	b.WriteString("# varvig: rules for coding agents\n\n")
	b.WriteString("This file is **generated and overwritten in full** on every `varvig init`\n")
	b.WriteString("and on every varvig upgrade. Edits here will be lost. Put your own agent\n")
	b.WriteString("instructions in AGENTS.md instead.\n\n")
	fmt.Fprintf(&b, "Source: varvig %s · intent schema v%d · surface %s\n\n",
		version, IntentSchemaVersion, surface)
	return b.String()
}

// bodyStart is the first heading of the body — the boundary between the
// version-bearing header and the version-independent body. bodyOf uses it to
// compare two files' bodies while ignoring the version line.
const bodyStart = "## What varvig is"

// bodyOf returns the version-independent body of a generated file (everything
// from the first section heading), or the whole string if the marker is absent.
func bodyOf(s string) string {
	if i := strings.Index(s, bodyStart); i >= 0 {
		return s[i:]
	}
	return s
}

// renderBody renders everything after the header. Its bytes are what the surface
// hash covers, so it must contain nothing version-dependent.
func renderBody(facts RepoFacts) string {
	var b strings.Builder

	section(&b, "What varvig is",
		"varvig is version control for parallel AI agents. Its core promise is that\n"+
			"nothing you do is destructive. You work inside a scoped, propose-only task:\n"+
			"you read and propose; a human decides what lands.")

	section(&b, "The one rule",
		"You hold **propose-only** credentials. You may PROPOSE changes. You may never\n"+
			"promote, force, rewrite, or delete. Promotion is a separate, human-gated step.")

	// Credential scope table.
	b.WriteString("## Your credentials\n\n")
	b.WriteString("| Capability | You can |\n|---|---|\n")
	for _, c := range CredentialScope {
		mark := "no"
		if c.Allowed {
			mark = "yes"
		}
		if c.Note != "" {
			mark += " — " + c.Note
		}
		fmt.Fprintf(&b, "| %s | %s |\n", c.Capability, mark)
	}
	b.WriteString("\n")

	section(&b, "Workflow",
		"1. **Read** within your scope (`read`, `log`, `verify`, `affected`).\n"+
			"2. **Propose** through the MCP gate (`mcp`) or a task credential (`task`).\n"+
			"   Every proposal is signed and records your intent.\n"+
			"3. **Gates run.** The repo's acceptance gates must pass.\n"+
			"4. **A human promotes.** You never move a ref yourself.")

	// Agent-facing commands.
	b.WriteString("## Commands you use\n\n")
	for _, c := range Commands {
		if !c.AgentFacing {
			continue
		}
		fmt.Fprintf(&b, "- **`%s`** — %s\n", c.Name, c.Summary)
		if c.Usage != "" {
			fmt.Fprintf(&b, "  - usage: `%s`\n", c.Usage)
		}
		for _, f := range c.Flags {
			if !f.AgentFacing {
				continue
			}
			fmt.Fprintf(&b, "  - `%s` — %s\n", f.Name, f.Summary)
		}
	}
	b.WriteString("\n")

	// Intent object.
	b.WriteString("## Recording intent\n\n")
	b.WriteString("Every proposal carries an intent record. These fields are yours to set:\n\n")
	for _, f := range IntentFields {
		if !f.AgentFacing {
			continue
		}
		req := "optional"
		if f.Required {
			req = "**required**"
		}
		fmt.Fprintf(&b, "- `%s` (%s) — %s\n", f.Name, req, f.Summary)
	}
	b.WriteString("\nEverything else in the record — authority, the read set, generator and\n")
	b.WriteString("tooling pins — is filled in for you and cannot be forged.\n\n")

	// Acceptance gates — resolved from the repo, or an explicit TODO.
	b.WriteString("## Acceptance gates\n\n")
	if len(facts.AcceptanceGates) == 0 && facts.TestCommand == "" {
		b.WriteString("TODO: no acceptance gates are configured in this repo. Until a gate is\n")
		b.WriteString("set, treat the repo's own tests as the bar your proposal must clear —\n")
		b.WriteString("ask which command runs them if it is not obvious.\n\n")
	} else {
		b.WriteString("Your proposal must pass these before it can land:\n\n")
		for _, g := range facts.AcceptanceGates {
			fmt.Fprintf(&b, "- gate: `%s`\n", g)
		}
		if facts.TestCommand != "" {
			fmt.Fprintf(&b, "- tests: `%s`\n", facts.TestCommand)
		}
		b.WriteString("\nNever try to bypass, weaken, or disable a gate.\n\n")
	}

	// Error catalog.
	b.WriteString("## When something is refused\n\n")
	for _, e := range Errors {
		fmt.Fprintf(&b, "- **%s** — %s\n  - why: %s\n  - do: %s\n", e.Code, e.What, e.Why, e.Do)
	}
	b.WriteString("\n")

	// Inline invariants (mirror of the AGENTS.md pointer; version-independent).
	section(&b, "Invariants (true regardless of version)",
		"- You hold propose-only credentials.\n"+
			"- You cannot force, rewrite, or delete anything.\n"+
			"- Every proposal must pass the repo's acceptance gates before it can land.")

	return b.String()
}

// section writes a `## title` heading and a body paragraph followed by a blank
// line, the one shape every prose section uses.
func section(b *strings.Builder, title, bodyText string) {
	fmt.Fprintf(b, "## %s\n\n%s\n\n", title, bodyText)
}

// PointerBlock is the fixed block appended once to AGENTS.md. It is
// version-independent: only invariants that hold across every version go here,
// so it never needs rewriting (that is what makes append-once safe).
func PointerBlock() string {
	return pointerMarker + "\n" +
		"## varvig\n\n" +
		"This repo uses varvig for version control. **Before any version control\n" +
		"operation, read `./" + GeneratedName + "`.** It is generated, current, and\n" +
		"required reading.\n\n" +
		"Invariants that hold regardless of version: you hold propose-only\n" +
		"credentials; you cannot force, rewrite, or delete anything; every\n" +
		"proposal must pass the repo's acceptance gates before it can land.\n"
}

// mdcPointer is the pointer block for a Cursor `.mdc` rule file: the same block
// under the frontmatter Cursor needs to always apply the rule. Only used when
// creating a fresh rule file in an existing `.cursor/rules/` directory.
func mdcPointer() string {
	return "---\n" +
		"description: varvig version-control rules for agents\n" +
		"alwaysApply: true\n" +
		"---\n\n" + PointerBlock()
}

// hasPointer reports whether AGENTS.md already carries the pointer — either the
// marker, or any literal mention of the generated file (users hand-write their
// own pointers, and a duplicate is exactly the clutter that gets a tool
// distrusted).
func hasPointer(existing string) bool {
	return strings.Contains(existing, pointerMarker) ||
		strings.Contains(existing, GeneratedName)
}

// readSurface extracts the `surface <hash>` token from a generated file's
// header, or "" if absent. Used by --check to compare against the current
// surface without regenerating the whole file.
func readSurface(content string) string {
	for _, line := range strings.Split(content, "\n") {
		if i := strings.Index(line, "surface "); i >= 0 && strings.HasPrefix(strings.TrimSpace(line), "Source:") {
			tok := strings.TrimSpace(line[i+len("surface "):])
			// The token runs to end of line; guard against trailing content.
			if sp := strings.IndexAny(tok, " \t"); sp >= 0 {
				tok = tok[:sp]
			}
			return tok
		}
	}
	return ""
}
